import type { Customer, DemoState, Inquiry, Order, Product } from "./types";

/* ═══ Clientes: kioscos, despensas, almacenes, bares ═══ */

export const demoCustomers: Customer[] = [
  {
    id: "c-kiosco-amigos",
    businessName: "Kiosco Los Amigos",
    contactName: "Juan Alvarez",
    phone: "5493492555101",
    address: "Av. Santa Fe 1280",
    city: "Rafaela",
    zone: "Rafaela centro",
    customerType: "Kiosco",
    priceList: "mayorista",
    creditLimit: 180000,
    currentDebt: 45000,
    status: "moroso",
    notes: "Compra 2 veces por semana. Paga los viernes. Buen volumen en bebidas y snacks.",
  },
  {
    id: "c-despensa-pedro",
    businessName: "Despensa Don Pedro",
    contactName: "Pedro Gimenez",
    phone: "5493492555102",
    address: "25 de Mayo 438",
    city: "Sunchales",
    zone: "Sunchales",
    customerType: "Despensa",
    priceList: "mayorista",
    creditLimit: 260000,
    currentDebt: 0,
    status: "activo",
    notes: "Pide por volumen cada lunes. Le interesan las promos de golosinas y galletitas.",
  },
  {
    id: "c-almacen-esquina",
    businessName: "Almacén La Esquina",
    contactName: "Marta Ruiz",
    phone: "5493492555103",
    address: "Bv. Lehmann 920",
    city: "Rafaela",
    zone: "Rafaela norte",
    customerType: "Almacén",
    priceList: "mayorista",
    creditLimit: 200000,
    currentDebt: 18000,
    status: "activo",
    notes: "Compra variado: bebidas, snacks y golosinas. Repone cada 10 días.",
  },
  {
    id: "c-bar-encuentro",
    businessName: "Bar El Encuentro",
    contactName: "Luis Peralta",
    phone: "5493492555104",
    address: "San Martín 63",
    city: "Lehmann",
    zone: "Lehmann",
    customerType: "Bar",
    priceList: "especial",
    creditLimit: 300000,
    currentDebt: 120000,
    status: "moroso",
    notes: "Volumen alto en bebidas y snacks de bar. Paga cada 15 días, necesita seguimiento.",
  },
  {
    id: "c-maxi-24hs",
    businessName: "Maxikiosco 24hs",
    contactName: "Sofia Molina",
    phone: "5493492555105",
    address: "Mitre 744",
    city: "Rafaela",
    zone: "Rafaela oeste",
    customerType: "Maxikiosco",
    priceList: "minorista",
    creditLimit: 100000,
    currentDebt: 0,
    status: "activo",
    notes: "Paga al contado. Compra semanal. Pide mucho helado en verano.",
  },
  {
    id: "c-almacen-rosa",
    businessName: "Almacén Doña Rosa",
    contactName: "Rosa Benítez",
    phone: "5493492555106",
    address: "Ruta 34 km 224",
    city: "Rafaela",
    zone: "Rafaela sur",
    customerType: "Almacén",
    priceList: "mayorista",
    creditLimit: 220000,
    currentDebt: 0,
    status: "activo",
    notes: "Compra por pallet cuando hay promociones. Fuerte en galletitas y alfajores.",
  },
];

/* ═══ Productos: catálogo de distribuidora de kiosco ═══ */

export const demoProducts: Product[] = [
  {
    id: "p-coca-500",
    sku: "BEB-001",
    name: "Coca-Cola 500ml pack x12",
    category: "Bebidas",
    unit: "pack",
    costPrice: 9100,
    stock: 48,
    minStock: 20,
    prices: { minorista: 14400, mayorista: 11800, especial: 11200 },
    active: true,
  },
  {
    id: "p-agua-500",
    sku: "BEB-002",
    name: "Agua mineral 500ml pack x12",
    category: "Bebidas",
    unit: "pack",
    costPrice: 4200,
    stock: 62,
    minStock: 25,
    prices: { minorista: 7200, mayorista: 5800, especial: 5400 },
    active: true,
  },
  {
    id: "p-fanta-500",
    sku: "BEB-003",
    name: "Fanta 500ml pack x12",
    category: "Bebidas",
    unit: "pack",
    costPrice: 8600,
    stock: 30,
    minStock: 15,
    prices: { minorista: 13800, mayorista: 11200, especial: 10600 },
    active: true,
  },
  {
    id: "p-alfajor-triple",
    sku: "GOL-010",
    name: "Alfajor triple caja x24",
    category: "Golosinas",
    unit: "caja",
    costPrice: 17800,
    stock: 22,
    minStock: 15,
    prices: { minorista: 28800, mayorista: 24000, especial: 22800 },
    active: true,
  },
  {
    id: "p-papas-grandes",
    sku: "SNK-020",
    name: "Papas fritas grandes caja x20",
    category: "Snacks",
    unit: "caja",
    costPrice: 23800,
    stock: 8,
    minStock: 10,
    prices: { minorista: 36000, mayorista: 30000, especial: 28500 },
    active: true,
  },
  {
    id: "p-galletitas-surtido",
    sku: "GAL-030",
    name: "Galletitas surtido caja x30",
    category: "Galletitas",
    unit: "caja",
    costPrice: 13200,
    stock: 14,
    minStock: 10,
    prices: { minorista: 21000, mayorista: 17500, especial: 16800 },
    active: true,
  },
  {
    id: "p-caramelos-surtido",
    sku: "GOL-040",
    name: "Caramelos surtido bolsa x100",
    category: "Golosinas",
    unit: "bolsa",
    costPrice: 6100,
    stock: 6,
    minStock: 12,
    prices: { minorista: 9500, mayorista: 7800, especial: 7200 },
    active: true,
  },
  {
    id: "p-chicles-caja",
    sku: "GOL-050",
    name: "Chicles caja x50",
    category: "Golosinas",
    unit: "caja",
    costPrice: 7800,
    stock: 35,
    minStock: 15,
    prices: { minorista: 12500, mayorista: 10200, especial: 9600 },
    active: true,
  },
  {
    id: "p-helado-palito",
    sku: "HEL-060",
    name: "Helado palito caja x24",
    category: "Helados",
    unit: "caja",
    costPrice: 21800,
    stock: 18,
    minStock: 20,
    prices: { minorista: 32400, mayorista: 27000, especial: 25200 },
    active: true,
  },
  {
    id: "p-jugo-caja",
    sku: "BEB-070",
    name: "Jugo en caja pack x12",
    category: "Bebidas",
    unit: "pack",
    costPrice: 6300,
    stock: 40,
    minStock: 18,
    prices: { minorista: 10800, mayorista: 8400, especial: 7800 },
    active: true,
  },
];

/* ═══ Consultas: típicas de clientes de kiosco ═══ */

export const demoInquiries: Inquiry[] = [
  {
    id: "i-001",
    customerId: "c-despensa-pedro",
    prospectName: "Despensa Don Pedro",
    channel: "WhatsApp",
    text: "Hola, pasame precio de alfajores triple y galletitas surtido, quiero reponer esta semana.",
    productHints: ["Alfajor triple caja x24", "Galletitas surtido caja x30"],
    status: "cotizada",
    owner: "Gabriel",
    nextAction: "Confirmar cantidades antes de las 17 hs.",
    followUpDate: "2026-07-22",
    createdAt: "2026-07-22",
  },
  {
    id: "i-002",
    customerId: "c-almacen-rosa",
    prospectName: "Almacén Doña Rosa",
    channel: "WhatsApp",
    text: "Tenes stock de caramelos surtido y chicles? Necesito precio por cantidad grande.",
    productHints: ["Caramelos surtido bolsa x100", "Chicles caja x50"],
    status: "seguimiento",
    owner: "Juan",
    nextAction: "Enviar promo por volumen de golosinas.",
    followUpDate: "2026-07-23",
    createdAt: "2026-07-21",
  },
  {
    id: "i-003",
    prospectName: "Kiosco Nuevo Centro",
    channel: "Instagram",
    text: "Hola, recién abro un kiosco en el centro. Me pasan lista de precios de bebidas y snacks?",
    productHints: ["Coca-Cola 500ml pack x12", "Papas fritas grandes caja x20"],
    status: "nueva",
    owner: "Gabriel",
    nextAction: "Pedir WhatsApp y armar lista personalizada.",
    followUpDate: "2026-07-22",
    createdAt: "2026-07-22",
  },
  {
    id: "i-004",
    customerId: "c-bar-encuentro",
    prospectName: "Bar El Encuentro",
    channel: "WhatsApp",
    text: "Cuánto me queda pendiente? Y pasame precio de Coca y Fanta pack x12, necesito para el finde.",
    productHints: ["Coca-Cola 500ml pack x12", "Fanta 500ml pack x12"],
    status: "respondida",
    owner: "Juan",
    nextAction: "Recordar saldo pendiente y armar pedido de bebidas.",
    followUpDate: "2026-07-24",
    createdAt: "2026-07-20",
  },
];

/* ═══ Pedidos demo ═══ */

export const demoOrders: Order[] = [
  {
    id: "o-001",
    number: "0001",
    customerId: "c-almacen-esquina",
    status: "entregado_sin_cobrar",
    lines: [
      { productId: "p-coca-500", quantity: 3, unitPrice: 11800 },
      { productId: "p-alfajor-triple", quantity: 2, unitPrice: 24000 },
    ],
    discount: 0,
    createdAt: "2026-07-21",
    dueDate: "2026-07-24",
    deliveryZone: "Rafaela norte",
    owner: "Gabriel",
    notes: "Entregado en el local. Falta transferencia.",
    paidAmount: 35400,
  },
  {
    id: "o-002",
    number: "0002",
    customerId: "c-kiosco-amigos",
    status: "confirmado",
    lines: [
      { productId: "p-coca-500", quantity: 4, unitPrice: 11800 },
      { productId: "p-papas-grandes", quantity: 2, unitPrice: 30000 },
      { productId: "p-helado-palito", quantity: 1, unitPrice: 27000 },
    ],
    discount: 0,
    createdAt: "2026-07-22",
    dueDate: "2026-07-27",
    deliveryZone: "Rafaela centro",
    owner: "Juan",
    notes: "Preparar antes del mediodía. Lleva mucho helado por el calor.",
    paidAmount: 0,
  },
  {
    id: "o-003",
    number: "0003",
    customerId: "c-bar-encuentro",
    status: "preparado",
    lines: [
      { productId: "p-coca-500", quantity: 6, unitPrice: 11200 },
      { productId: "p-fanta-500", quantity: 4, unitPrice: 10600 },
      { productId: "p-papas-grandes", quantity: 3, unitPrice: 28500 },
    ],
    discount: 5000,
    createdAt: "2026-07-22",
    dueDate: "2026-07-29",
    deliveryZone: "Lehmann",
    owner: "Gabriel",
    notes: "Sale en reparto de la tarde. Descuento por volumen.",
    paidAmount: 0,
  },
  {
    id: "o-004",
    number: "0004",
    customerId: "c-maxi-24hs",
    status: "pagado",
    lines: [
      { productId: "p-galletitas-surtido", quantity: 3, unitPrice: 21000 },
      { productId: "p-chicles-caja", quantity: 4, unitPrice: 12500 },
      { productId: "p-jugo-caja", quantity: 2, unitPrice: 10800 },
    ],
    discount: 0,
    createdAt: "2026-07-22",
    dueDate: "2026-07-22",
    deliveryZone: "Rafaela oeste",
    owner: "Juan",
    notes: "Pagado por transferencia al momento de entrega.",
    paidAmount: 134600,
  },
];

export const initialDemoState: DemoState = {
  customers: demoCustomers,
  products: demoProducts,
  inquiries: demoInquiries,
  orders: demoOrders,
};
