import type { Customer, DemoState, Order, Product } from "./types";

export const demoCustomers: Customer[] = [
  {
    id: "c-maribel-benitez",
    code: "181 / 0",
    businessName: "MARIBEL BENITEZ",
    contactName: "Maribel Benitez",
    phone: "",
    address: "CLUCELLAS",
    city: "RAFAELA",
    postalCode: "2300",
    province: "SANTA FE",
    zone: "Rafaela y zona",
    customerType: "Comercio",
    priceList: "mayorista",
    creditLimit: 0,
    currentDebt: 0,
    status: "activo",
    notes: "Cliente de demostración tomado del documento de referencia.",
  },
  {
    id: "c-almacen-centro",
    code: "205 / 0",
    businessName: "ALMACEN DEL CENTRO",
    contactName: "Laura Gomez",
    phone: "5493492000001",
    address: "Belgrano 325",
    city: "RAFAELA",
    postalCode: "2300",
    province: "SANTA FE",
    zone: "Rafaela centro",
    customerType: "Almacen",
    priceList: "mayorista",
    creditLimit: 0,
    currentDebt: 0,
    status: "activo",
    notes: "Datos ficticios para demostracion.",
  },
  {
    id: "c-despensa-san-martin",
    code: "219 / 0",
    businessName: "DESPENSA SAN MARTIN",
    contactName: "Diego Peralta",
    phone: "5493492000002",
    address: "San Martin 1180",
    city: "RAFAELA",
    postalCode: "2300",
    province: "SANTA FE",
    zone: "Rafaela norte",
    customerType: "Despensa",
    priceList: "mayorista",
    creditLimit: 0,
    currentDebt: 0,
    status: "activo",
    notes: "Datos ficticios para demostracion.",
  },
];

function product(
  sku: string,
  name: string,
  category: string,
  unit: string,
  price: number,
  stock: number,
  allowsDecimals = false,
): Product {
  return {
    id: `p-${sku}`,
    sku,
    name,
    category,
    unit,
    costPrice: 0,
    stock,
    minStock: allowsDecimals ? 20 : 30,
    prices: { minorista: price, mayorista: price, especial: price },
    active: true,
    allowsDecimals,
  };
}

export const demoProducts: Product[] = [
  product("007", "CUARTIROLO AL VACIO RAMOLAC", "Lacteos", "kg", 7750, 160, true),
  product("724", "SANDWICHERA LA CASONA", "Fiambres", "kg", 4449, 140, true),
  product("719", "SALCHICHA L. C.", "Fiambres", "un.", 1099, 300),
  product("524", "MAYONESA C/DIA X 125 G.", "Aderezos", "un.", 489, 300),
  product("383", "GALL. C/CHIPS DE CHOC. X 120", "Galletitas", "un.", 638.81, 240),
  product("302", "PRE-PIZZA X 2 SAN RAFAEL", "Panificados", "un.", 2052, 180),
  product("341", "PAN LACTAL X 500 GR.", "Panificados", "un.", 2050, 180),
  product("328", "GALL. TIPO OREO X 220 G LA PROVIDENCIA", "Galletitas", "un.", 1651, 220),
  product("332", "TAPA ALFAJOR X 3 KG.FACHITAS", "Reposteria", "un.", 19433, 90),
  product("1054", "NUEZ MOSC. MOLIDA PREMIUM X 1 KG. DON ILMO", "Condimentos", "un.", 30376.64, 70),
  product("400", "ACEITUNAS SACHET X 100 GR.", "Conservas", "un.", 797.5, 260),
  product("606", "BOLITAS DE CHOCO. X 1 GK. ECOSAN", "Reposteria", "un.", 5515.65, 90),
  product("636", "CEREAL AZUCARADO X 1 KG ECOSAN", "Cereales", "un.", 8500, 90),
  product("605", "ANILLOS FRUTADOS X 1 KG", "Cereales", "un.", 5793.91, 90),
  product("569", "CHIPS DE CHOC. NEGRO X KG. DON ILMO", "Reposteria", "kg", 14241.7, 90, true),
  product("516", "LEVADURA X 50 G.", "Panificados", "un.", 950, 260),
  product("313", "PAN RALLADO X 10 KG SR PAN", "Panificados", "un.", 19111.73, 80),
];

export const demoOrders: Order[] = [
  {
    id: "o-000001",
    number: "000001",
    customerId: "c-maribel-benitez",
    status: "confirmado",
    lines: [
      { productId: "p-007", packages: 1, quantity: 4.25, unitPrice: 7750 },
      { productId: "p-724", packages: 1, quantity: 3.8, unitPrice: 4449 },
      { productId: "p-719", packages: 24, quantity: 24, unitPrice: 1099 },
      { productId: "p-524", packages: 20, quantity: 20, unitPrice: 489 },
      { productId: "p-383", packages: 10, quantity: 10, unitPrice: 638.81 },
      { productId: "p-302", packages: 4, quantity: 4, unitPrice: 2052 },
      { productId: "p-341", packages: 2, quantity: 2, unitPrice: 2050 },
      { productId: "p-328", packages: 5, quantity: 5, unitPrice: 1651 },
      { productId: "p-332", packages: 1, quantity: 1, unitPrice: 19433 },
      { productId: "p-1054", packages: 1, quantity: 1, unitPrice: 30376.64 },
      { productId: "p-400", packages: 5, quantity: 5, unitPrice: 797.5 },
      { productId: "p-606", packages: 1, quantity: 1, unitPrice: 5515.65 },
      { productId: "p-636", packages: 1, quantity: 1, unitPrice: 8500 },
      { productId: "p-605", packages: 1, quantity: 1, unitPrice: 5793.91 },
      { productId: "p-569", packages: 1, quantity: 1, unitPrice: 14241.7 },
      { productId: "p-516", packages: 5, quantity: 5, unitPrice: 950 },
      { productId: "p-313", packages: 1, quantity: 1, unitPrice: 19111.73 },
    ],
    discount: 0,
    createdAt: "2026-09-09",
    dueDate: "2026-09-09",
    deliveryZone: "Rafaela y zona",
    owner: "1",
    seller: "1",
    saleCondition: "CUENTA CORRIENTE",
    externalReference: "Remito B 000900117206",
    notes: "Pedido de demostracion reconstruido a partir del documento entregado.",
    paidAmount: 0,
  },
];

export const initialDemoState: DemoState = {
  customers: demoCustomers,
  products: demoProducts,
  inquiries: [],
  orders: demoOrders,
};
